### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by hey-red** [pidydx/libmagicwin64#1]
Can you update binaries?

**Comment by pidydx** [comment]
Unfortunately I can't at the moment, but I can see if I can remember what I did and provide more complete instructions if I find some time.

**Comment by hey-red** [comment]
@pidydx It would be nice. I'm tried to build standalone libmagic with msys2, but she still had a dependence on msys.

**Comment by nscaife** [comment]
I also needed a fresh copy of these.  I put the build process and binaries in a separate repo.  https://github.com/nscaife/file-windows

**Comment by pidydx** [comment]
@nscaife Thanks for providing an updated link!
