### ISSUE TITLE
windows 10 x64 issue

### ISSUE THREAD

**Issue by LeviZell** [pidydx/libmagicwin64#2]
I have done this, but I still can't get python-magic to work. 

Does it have something to do with this line:
file_magic = magic.Magic(magic_file="c:\path\to\magic.mgc")

Where does this go? Just after importing magic?

**Comment by pidydx** [comment]
Unfortunately it has been ages since I have done this and can't really update right now.  However, there appears to be a more updated and detailed version of what I was attempting here in this repo: https://github.com/nscaife/file-windows

**Comment by jienkles** [comment]
@LeviZell 

Hi there did u get anywhere as im having a simiar problem 

manythanks
d

**Comment by Speeeddy** [comment]
You can perhaps try a different pip module called python-magic-bin
pip uninstall python-magic
pip install python-magic-bin

**Comment by clementin35** [comment]
@Speeeddy this works for me. Thank you very much...

**Comment by Koubae** [comment]
Worked fine just after adding all of the 3 files: libgnurx / magic.mgc / magic1.dll into 
C:\Windows\System32
